
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

import java_cup.runtime.*;
import java.util.Map;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Sintactico extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Sintactico() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Sintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\022\000\002\002\004\000\002\002\011\000\002\003" +
    "\004\000\002\003\003\000\002\004\010\000\002\005\004" +
    "\000\002\005\003\000\002\006\006\000\002\011\005\000" +
    "\002\011\005\000\002\011\004\000\002\011\004\000\002" +
    "\011\004\000\002\011\005\000\002\011\003\000\002\007" +
    "\004\000\002\007\003\000\002\010\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\056\000\004\014\004\001\002\000\004\004\011\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\006\004\ufffe\012\ufffe\001\002\000\006\004\011\012" +
    "\021\001\002\000\004\006\012\001\002\000\004\012\013" +
    "\001\002\000\004\005\014\001\002\000\004\013\015\001" +
    "\002\000\004\007\016\001\002\000\006\004\ufffd\012\ufffd" +
    "\001\002\000\006\004\uffff\012\uffff\001\002\000\006\010" +
    "\046\012\021\001\002\000\004\005\023\001\002\000\006" +
    "\010\ufffb\012\ufffb\001\002\000\020\011\031\014\025\016" +
    "\033\017\024\020\032\021\027\022\030\001\002\000\020" +
    "\011\031\014\025\016\033\017\024\020\032\021\027\022" +
    "\030\001\002\000\004\012\042\001\002\000\004\007\041" +
    "\001\002\000\020\011\031\014\025\016\033\017\024\020" +
    "\032\021\027\022\030\001\002\000\020\011\031\014\025" +
    "\016\033\017\024\020\032\021\027\022\030\001\002\000" +
    "\022\007\ufff3\011\ufff3\014\ufff3\016\ufff3\017\ufff3\020\ufff3" +
    "\021\ufff3\022\ufff3\001\002\000\020\011\031\014\025\016" +
    "\033\017\024\020\032\021\027\022\030\001\002\000\020" +
    "\011\031\014\025\016\033\017\024\020\032\021\027\022" +
    "\030\001\002\000\020\011\031\014\025\016\033\017\024" +
    "\020\032\021\027\022\030\001\002\000\022\007\ufff9\011" +
    "\ufff9\014\ufff9\016\ufff9\017\ufff9\020\ufff9\021\ufff9\022\ufff9" +
    "\001\002\000\022\007\ufff7\011\ufff7\014\ufff7\016\ufff7\017" +
    "\ufff7\020\ufff7\021\ufff7\022\ufff7\001\002\000\022\007\ufff5" +
    "\011\ufff5\014\ufff5\016\ufff5\017\ufff5\020\ufff5\021\ufff5\022" +
    "\ufff5\001\002\000\022\007\ufff6\011\ufff6\014\ufff6\016\ufff6" +
    "\017\ufff6\020\ufff6\021\ufff6\022\ufff6\001\002\000\006\010" +
    "\ufffa\012\ufffa\001\002\000\004\015\043\001\002\000\022" +
    "\007\ufff4\011\ufff4\014\ufff4\016\ufff4\017\ufff4\020\ufff4\021" +
    "\ufff4\022\ufff4\001\002\000\020\011\031\014\025\016\033" +
    "\017\024\020\032\021\027\022\030\001\002\000\022\007" +
    "\ufff8\011\ufff8\014\ufff8\016\ufff8\017\ufff8\020\ufff8\021\ufff8" +
    "\022\ufff8\001\002\000\004\010\050\001\002\000\006\010" +
    "\ufffc\012\ufffc\001\002\000\004\012\052\001\002\000\006" +
    "\012\052\015\057\001\002\000\004\006\054\001\002\000" +
    "\006\012\ufff1\015\ufff1\001\002\000\004\011\055\001\002" +
    "\000\004\007\056\001\002\000\006\012\ufff0\015\ufff0\001" +
    "\002\000\004\002\000\001\002\000\006\012\ufff2\015\ufff2" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\056\000\004\002\004\001\001\000\006\003\007\004" +
    "\006\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\004\016\005\017\006\021\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\006\046\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\011\025\001\001\000\004\011\043\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\011\037" +
    "\001\001\000\004\011\036\001\001\000\002\001\001\000" +
    "\004\011\035\001\001\000\004\011\033\001\001\000\004" +
    "\011\034\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\011\044\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\007\050\010\052\001\001\000\004\010\057\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    Arboles arboles=new Arboles();
    //funcion de recuperacion de errores
    public void syntax_error(Symbol s){
        System.out.println("Unexpected token: "+s.value);
    }
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        System.out.println("Fatal error, unexcepted token: "+s.value);
    }

    public void myFunction(){
    //......
        
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Sintactico$actions {
  private final Sintactico parser;

  /** Constructor */
  CUP$Sintactico$actions(Sintactico parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Sintactico$do_action_part00000000(
    int                        CUP$Sintactico$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico$parser,
    java.util.Stack            CUP$Sintactico$stack,
    int                        CUP$Sintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintactico$result;

      /* select the action based on the action number */
      switch (CUP$Sintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		RESULT = start_val;
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintactico$parser.done_parsing();
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= PR_PARENTESIS_A conjuntos expresiones PR_SEPARADOR PR_SEPARADOR lexemas PR_PARENTESIS_C 
            {
              Object RESULT =null;
		
    
    arboles.mostrar();

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-6)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // conjuntos ::= conjuntos conjunto 
            {
              Object RESULT =null;
		


              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("conjuntos",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // conjuntos ::= conjunto 
            {
              Object RESULT =null;
		


              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("conjuntos",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // conjunto ::= PR_CONJ PR_DOPOINT PR_VAR PR_ASIG PR_RANGECONJ PR_ENDLINE 
            {
              Object RESULT =null;
		int nombreConjleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int nombreConjright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String nombreConj = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int lexConjleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int lexConjright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String lexConj = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		  
    tokens.tk.put(nombreConj,lexConj);

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("conjunto",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // expresiones ::= expresiones expresion 
            {
              Object RESULT =null;
		


              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresiones",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // expresiones ::= expresion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresiones",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // expresion ::= PR_VAR PR_ASIG expresionRegular PR_ENDLINE 
            {
              Object RESULT =null;
		int nombRegexleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int nombRegexright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String nombRegex = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int regexleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int regexright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object regex = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
    
    arboles.insertar((String)nombRegex,(NodoArbol)regex);

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expresionRegular ::= PR_OR expresionRegular expresionRegular 
            {
              Object RESULT =null;
		int regexleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int regexright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object regex = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int regleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int regright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object reg = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    boolean anulable=true;
    if(((NodoArbol)regex).getAnulable()|((NodoArbol)reg).getAnulable()){
        anulable=true;
    }else{
        anulable=false;
    }
    NodoArbol nodo=new NodoArbol("|",anulable,0, 0);
    nodo.setIzq((NodoArbol)regex);
    nodo.setDer(((NodoArbol)reg));
    RESULT=nodo;
    

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresionRegular",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expresionRegular ::= PR_AND expresionRegular expresionRegular 
            {
              Object RESULT =null;
		int regexleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int regexright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object regex = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int regleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int regright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object reg = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    boolean anulable=true;
    if(((NodoArbol)regex).getAnulable()& ((NodoArbol)reg).getAnulable()){
        anulable=true;
    }else{
        anulable=false;
    }
    NodoArbol nodo=new NodoArbol(".",anulable,0, 0);
    nodo.setIzq(((NodoArbol)regex));
    nodo.setDer(((NodoArbol)reg));
    RESULT=nodo;


              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresionRegular",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // expresionRegular ::= PR_PLUS expresionRegular 
            {
              Object RESULT =null;
		int regexleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int regexright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object regex = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    boolean anulable=((NodoArbol)regex).getAnulable();
    NodoArbol nodo=new NodoArbol("+",anulable,0, 0);
    nodo.setIzq(((NodoArbol)regex));
    RESULT=nodo;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresionRegular",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // expresionRegular ::= PR_QUEST expresionRegular 
            {
              Object RESULT =null;
		int regexleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int regexright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object regex = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		

    NodoArbol nodo=new NodoArbol("?",true,0, 0);
    nodo.setIzq(((NodoArbol)regex));
    RESULT=nodo;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresionRegular",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // expresionRegular ::= PR_MULT expresionRegular 
            {
              Object RESULT =null;
		int regexleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int regexright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object regex = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
   
    NodoArbol nodo=new NodoArbol("*",true,0, 0);
    nodo.setIzq(((NodoArbol)regex));
    RESULT=nodo;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresionRegular",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // expresionRegular ::= PR_PARENTESIS_A PR_VAR PR_PARENTESIS_C 
            {
              Object RESULT =null;
		int nombreConjleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int nombreConjright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String nombreConj = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
    NodoArbol nodo=new NodoArbol(nombreConj,false,0, 0);
    RESULT=nodo;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresionRegular",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // expresionRegular ::= PR_LEXEMA 
            {
              Object RESULT =null;
		int lexemaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int lexemaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String lexema = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    NodoArbol nodo=new NodoArbol(lexema,false,0, 0);
    RESULT=nodo;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresionRegular",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // lexemas ::= lexemas lexema 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lexemas",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // lexemas ::= lexema 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lexemas",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // lexema ::= PR_VAR PR_DOPOINT PR_LEXEMA PR_ENDLINE 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lexema",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Sintactico$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Sintactico$do_action(
    int                        CUP$Sintactico$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico$parser,
    java.util.Stack            CUP$Sintactico$stack,
    int                        CUP$Sintactico$top)
    throws java.lang.Exception
    {
              return CUP$Sintactico$do_action_part00000000(
                               CUP$Sintactico$act_num,
                               CUP$Sintactico$parser,
                               CUP$Sintactico$stack,
                               CUP$Sintactico$top);
    }
}

}
