
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PR_LEXEMA = 8;
  public static final int PR_VAR = 9;
  public static final int EOF = 0;
  public static final int PR_PARENTESIS_C = 12;
  public static final int PR_RANGECONJ = 10;
  public static final int PR_PARENTESIS_A = 11;
  public static final int PR_ENDLINE = 5;
  public static final int PR_CONJ = 2;
  public static final int error = 1;
  public static final int PR_DOPOINT = 4;
  public static final int PR_REGEX = 6;
  public static final int PR_SEPARADOR = 7;
  public static final int PR_ASIG = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PR_CONJ",
  "PR_ASIG",
  "PR_DOPOINT",
  "PR_ENDLINE",
  "PR_REGEX",
  "PR_SEPARADOR",
  "PR_LEXEMA",
  "PR_VAR",
  "PR_RANGECONJ",
  "PR_PARENTESIS_A",
  "PR_PARENTESIS_C"
  };
}

